name: docker-peptide

on:
  push:
    tags:
      - "v*.*.*"
env:
  IMAGE_NAME: ghcr.io/polymerdao/optimism

jobs:
  docker-build-peptide:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.build-ref }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{raw}}
        labels: |
          org.opencontainers.image.source=https://github.com/polymerdao/optimism-dev
          org.opencontainers.image.title=polymer
          org.opencontainers.image.url=https://github.com/polymerdao/optimism-dev

    - name: Authenticate Docker
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: make golang-docker
      env:
        REGISTRY: ghcr.io
        REPOSITORY: polymerdao/optimism

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/polymerdao/optimism/op-node:latest
          ghcr.io/polymerdao/optimism/op-batcher:latest
          ghcr.io/polymerdao/optimism/op-proposer:latest
          ghcr.io/polymerdao/optimism/op-challenger:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
